export const capabilities = {
  projectView: "project:view",
  projectCreate: "project:create",
  projectEdit: "project:edit",
  projectEditInfo: "project:edit_info",
  projectAssignMember: "project:assign_member",
  generationStart: "generation:start",
  exportCreate: "export:create",
  billingPurchase: "billing:purchase",
  billingRefund: "billing:refund",
  opsSettle: "ops:settle",
  teamMemberRead: "team:member:read",
  teamMemberManageAll: "team:member:manage_all",
  teamMemberManageGroup: "team:member:manage_group",
  teamGroupCreate: "team:group:create",
  teamGroupUpdate: "team:group:update",
  teamGroupDelete: "team:group:delete",
  teamCreditAllocateAll: "team:credit:allocate_all",
  teamCreditAllocateGroup: "team:credit:allocate_group",
  teamDashboardViewAll: "team:dashboard:view_all",
  teamDashboardViewGroup: "team:dashboard:view_group",
  novelAdaptScript: "novel:adapt_script",
  scriptAssetCreate: "script_asset:create",
  scriptAssetDownload: "script_asset:download",
  scriptAssetDelete: "script_asset:delete",
  characterScenePropCreate: "character_scene_prop:create",
  characterScenePropEdit: "character_scene_prop:edit",
  characterScenePropDownload: "character_scene_prop:download",
  characterScenePropDelete: "character_scene_prop:delete",
  episodeAssetCreate: "episode_asset:create",
  episodeAssetEdit: "episode_asset:edit",
  episodeAssetDownload: "episode_asset:download",
  episodeAssetDelete: "episode_asset:delete",
  toolboxUse: "toolbox:use",
  teamKnowledgeTemplateCreate: "team_knowledge_template:create",
  teamKnowledgeTemplateEdit: "team_knowledge_template:edit",
  teamKnowledgeTemplateUse: "team_knowledge_template:use",
  teamKnowledgeTemplateDelete: "team_knowledge_template:delete",
} as const;

export type Capability = (typeof capabilities)[keyof typeof capabilities];

export const p0Capabilities = Object.values(capabilities);
