-- Explicit catalog snapshot. Apply with `npm run admin:catalog:apply` when promoting admin configuration.
UPDATE membership_plans
SET display_metadata_json = COALESCE(display_metadata_json, '{}'::jsonb) - 'isRecommended',
    updated_at = now()
WHERE visibility = 'public'
  AND code <> 'professional_monthly'
  AND display_metadata_json ->> 'isRecommended' = 'true';

UPDATE membership_plans
SET status = 'archived',
    updated_at = now()
WHERE code = 'basic_quarter'
  AND status <> 'archived';

WITH configured_plans (
  code,
  display_name,
  tier,
  period_unit,
  period_count,
  amount_minor,
  currency,
  gift_credits,
  seat_limit,
  entitlements_json,
  priority_rules_json,
  display_metadata_json,
  status,
  visibility,
  usage_scene
) AS (
  VALUES
    (
      'experience_weekly',
      '体验套餐（基础版）',
      'experience',
      'day',
      7,
      990,
      'CNY',
      7100,
      1,
      '["canvas_access","priority_generation","team_asset_library","full_flow_agent"]'::jsonb,
      '{"modelFamilies":["seedance-lite"]}'::jsonb,
      '{"note":"基础无团队功能、画布限时开放、后续限制个别模型与功能使用","features":["有效期7天"],"sortOrder":10}'::jsonb,
      'active',
      'public',
      'purchase'
    ),
    (
      'basic_monthly',
      '月度套餐（基础版）',
      'experience',
      'month',
      1,
      5990,
      'CNY',
      47900,
      1,
      '["canvas_access","priority_generation","full_flow_agent"]'::jsonb,
      '{"modelFamilies":["seedance"]}'::jsonb,
      '{"note":"基础无团队功能、画布限时开放、后续限制某些模型与功能使用","features":[],"sortOrder":20}'::jsonb,
      'active',
      'public',
      'purchase'
    ),
    (
      '222',
      '季度套餐（基础版）',
      'experience',
      'quarter',
      1,
      19990,
      'CNY',
      168490,
      1,
      '["canvas_access","priority_generation","full_flow_agent"]'::jsonb,
      '{}'::jsonb,
      '{"note":"基础无团队功能、画布限时开放、后续限制个别模型与功能使用","features":[],"sortOrder":30}'::jsonb,
      'active',
      'public',
      'purchase'
    ),
    (
      'basic_year',
      '年度套餐（基础版）',
      'experience',
      'year',
      1,
      59990,
      'CNY',
      490000,
      1,
      '["canvas_access","priority_generation","full_flow_agent"]'::jsonb,
      '{}'::jsonb,
      '{"note":"基础无团队功能、画布限时开放、后续限制个别模型与功能使用","features":[],"sortOrder":50}'::jsonb,
      'active',
      'public',
      'purchase'
    ),
    (
      'professional_monthly',
      '月度套餐（专业版）',
      'professional',
      'month',
      1,
      9990,
      'CNY',
      81900,
      50,
      '["canvas_access","priority_generation","team_asset_library","team_member_management","full_flow_agent"]'::jsonb,
      '{}'::jsonb,
      '{"note":"所有功能与模型","features":[],"sortOrder":60,"isRecommended":true,"recommendationLabel":"热门"}'::jsonb,
      'active',
      'public',
      'purchase'
    ),
    (
      'professional_quarter',
      '季度套餐（专业版）',
      'professional',
      'quarter',
      1,
      29990,
      'CNY',
      250400,
      50,
      '["canvas_access","priority_generation","team_asset_library","team_member_management","full_flow_agent"]'::jsonb,
      '{}'::jsonb,
      '{"note":"所有功能与模型","features":[],"sortOrder":70,"recommendationLabel":"推荐"}'::jsonb,
      'active',
      'public',
      'purchase'
    ),
    (
      'professional_year',
      '年度套餐（专业版）',
      'professional',
      'year',
      1,
      89990,
      'CNY',
      717400,
      50,
      '["canvas_access","priority_generation","team_asset_library","team_member_management","full_flow_agent"]'::jsonb,
      '{"modelFamilies":["seedance"],"queuePriority":1}'::jsonb,
      '{"note":"所有功能与模型","features":[],"sortOrder":80,"recommendationLabel":"推荐"}'::jsonb,
      'active',
      'public',
      'purchase'
    )
)
INSERT INTO membership_plans (
  id,
  code,
  display_name,
  tier,
  period_unit,
  period_count,
  amount_minor,
  currency,
  gift_credits,
  seat_limit,
  entitlements_json,
  priority_rules_json,
  display_metadata_json,
  status,
  visibility,
  usage_scene,
  valid_from,
  valid_until
)
SELECT
  md5('membership-plan:' || code)::uuid,
  code,
  display_name,
  tier,
  period_unit,
  period_count,
  amount_minor,
  currency,
  gift_credits,
  seat_limit,
  entitlements_json,
  priority_rules_json,
  display_metadata_json,
  status,
  visibility,
  usage_scene,
  NULL,
  NULL
FROM configured_plans
ON CONFLICT (code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  tier = EXCLUDED.tier,
  period_unit = EXCLUDED.period_unit,
  period_count = EXCLUDED.period_count,
  amount_minor = EXCLUDED.amount_minor,
  currency = EXCLUDED.currency,
  gift_credits = EXCLUDED.gift_credits,
  seat_limit = EXCLUDED.seat_limit,
  entitlements_json = EXCLUDED.entitlements_json,
  priority_rules_json = EXCLUDED.priority_rules_json,
  display_metadata_json = EXCLUDED.display_metadata_json,
  status = EXCLUDED.status,
  visibility = EXCLUDED.visibility,
  usage_scene = EXCLUDED.usage_scene,
  valid_from = EXCLUDED.valid_from,
  valid_until = EXCLUDED.valid_until,
  updated_at = now()
WHERE (
  membership_plans.display_name,
  membership_plans.tier,
  membership_plans.period_unit,
  membership_plans.period_count,
  membership_plans.amount_minor,
  membership_plans.currency,
  membership_plans.gift_credits,
  membership_plans.seat_limit,
  membership_plans.entitlements_json,
  membership_plans.priority_rules_json,
  membership_plans.display_metadata_json,
  membership_plans.status,
  membership_plans.visibility,
  membership_plans.usage_scene,
  membership_plans.valid_from,
  membership_plans.valid_until
) IS DISTINCT FROM (
  EXCLUDED.display_name,
  EXCLUDED.tier,
  EXCLUDED.period_unit,
  EXCLUDED.period_count,
  EXCLUDED.amount_minor,
  EXCLUDED.currency,
  EXCLUDED.gift_credits,
  EXCLUDED.seat_limit,
  EXCLUDED.entitlements_json,
  EXCLUDED.priority_rules_json,
  EXCLUDED.display_metadata_json,
  EXCLUDED.status,
  EXCLUDED.visibility,
  EXCLUDED.usage_scene,
  EXCLUDED.valid_from,
  EXCLUDED.valid_until
);

WITH configured_packages (
  code,
  display_name,
  credits,
  amount_minor,
  currency,
  status,
  subtitle,
  gift_credits,
  badge,
  sort_order,
  metadata_json
) AS (
  VALUES
    ('direct_recharge_9.9', '9.9积分直充', 9000, 990, 'CNY', 'active', '仅增加积分，不延长会员有效期', 0, NULL, 6, '{"kind":"direct_recharge"}'::jsonb),
    ('direct_recharge_99.9', '99.9 积分直充', 99900, 9990, 'CNY', 'active', '仅增加积分，不延长会员有效期', 0, NULL, 8, '{"kind":"direct_recharge"}'::jsonb),
    ('direct_recharge_199.9', '199.9 积分直充', 204000, 19990, 'CNY', 'active', '仅增加积分，不延长会员有效期', 0, NULL, 9, '{"kind":"direct_recharge"}'::jsonb),
    ('direct_recharge_399.9', '399.9 积分直充', 416000, 39990, 'CNY', 'active', '仅增加积分，不延长会员有效期', 0, NULL, 10, '{"kind":"direct_recharge"}'::jsonb),
    ('direct_recharge_599.9', '599.9 积分直充', 624000, 59990, 'CNY', 'active', '仅增加积分，不延长会员有效期', 0, NULL, 50, '{"kind":"direct_recharge"}'::jsonb),
    ('direct_recharge_999.9', '999.9 积分直充', 1060000, 99990, 'CNY', 'active', '仅增加积分，不延长会员有效期', 0, NULL, 60, '{"kind":"direct_recharge"}'::jsonb)
)
INSERT INTO credit_packages (
  id,
  code,
  display_name,
  credits,
  amount_minor,
  currency,
  status,
  valid_from,
  valid_until,
  subtitle,
  gift_credits,
  badge,
  sort_order,
  metadata_json
)
SELECT
  md5('credit-package:' || code)::uuid,
  code,
  display_name,
  credits,
  amount_minor,
  currency,
  status,
  NULL,
  NULL,
  subtitle,
  gift_credits,
  badge,
  sort_order,
  metadata_json
FROM configured_packages
ON CONFLICT (code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  credits = EXCLUDED.credits,
  amount_minor = EXCLUDED.amount_minor,
  currency = EXCLUDED.currency,
  status = EXCLUDED.status,
  valid_from = EXCLUDED.valid_from,
  valid_until = EXCLUDED.valid_until,
  subtitle = EXCLUDED.subtitle,
  gift_credits = EXCLUDED.gift_credits,
  badge = EXCLUDED.badge,
  sort_order = EXCLUDED.sort_order,
  metadata_json = EXCLUDED.metadata_json,
  updated_at = now()
WHERE (
  credit_packages.display_name,
  credit_packages.credits,
  credit_packages.amount_minor,
  credit_packages.currency,
  credit_packages.status,
  credit_packages.valid_from,
  credit_packages.valid_until,
  credit_packages.subtitle,
  credit_packages.gift_credits,
  credit_packages.badge,
  credit_packages.sort_order,
  credit_packages.metadata_json
) IS DISTINCT FROM (
  EXCLUDED.display_name,
  EXCLUDED.credits,
  EXCLUDED.amount_minor,
  EXCLUDED.currency,
  EXCLUDED.status,
  EXCLUDED.valid_from,
  EXCLUDED.valid_until,
  EXCLUDED.subtitle,
  EXCLUDED.gift_credits,
  EXCLUDED.badge,
  EXCLUDED.sort_order,
  EXCLUDED.metadata_json
);
