ALTER TABLE ai_model_configs
  DROP CONSTRAINT IF EXISTS ai_model_configs_provider_protocol_check;

ALTER TABLE ai_model_configs
  ADD CONSTRAINT ai_model_configs_provider_protocol_check CHECK (provider_protocol IN (
    'creator_dev',
    'openai_images',
    'openai_compatible_chat',
    'volcengine_ark_video',
    'aliyun_bailian_video',
    'globalaiopc_video',
    'lingdong_api',
    'custom_http'
  ));

WITH globalaiopc_configs AS (
  SELECT
    *
  FROM (
    VALUES
      (
        'sd2_manxue',
        'sd2_manxue 满血版',
        'sd2_manxue',
        'globalaiopc_sd2_manxue',
        '/v1/sd2_manxue/videos',
        '["video.text_to_video","video.image_to_video","video.first_last_frame_to_video","video.reference_image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"lastFrame":true,"referenceImages":true,"referenceVideo":false,"referenceAudio":true,"audio":true,"asyncPolling":true,"modelFamily":"sd2_manxue","membershipPriorityEligible":true}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"首帧图","type":"file","required":false},"lastFrame":{"label":"尾帧图","type":"file","required":false},"referenceImages":{"label":"参考图","type":"file[]","required":false,"maximum":9},"referenceAudio":{"label":"参考音频","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"ratio","required":false,"options":["21:9","16:9","4:3","1:1","3:4","9:16"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720p","1080p","2k","4k"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"integer","providerKey":"duration","required":false,"minimum":4,"maximum":15}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":5}'::jsonb,
        '{"unit":"video","baseCredits":160,"durationMultipliers":{"4":0.9,"5":1,"10":1.8,"15":2.6},"resolutionMultipliers":{"720p":1,"1080p":1.35,"2k":1.8,"4k":2.6}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":9,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsReferenceImages":true,"supportsReferenceAudio":true,"minDurationSec":4,"maxDurationSec":15,"supportedRatios":["21:9","16:9","4:3","1:1","3:4","9:16"],"supportedResolutions":["720p","1080p","2k","4k"],"allowedMimeTypes":["image/jpeg","image/png","image/webp","audio/mpeg","audio/wav"]}'::jsonb,
        '{"label":"sd2_manxue 满血版","group":"GlobalAiOpc","recommended":true,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","modelKind":"video.reference","modelKindLabel":"参考生视频","supportedModes":["text_to_video","image_to_video","first_last_frame_to_video","reference_image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/sd2-manxue/sd2-manxue-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        30,
        'GlobalAiOpc sd2_manxue 普通系列。平台配置使用统一模型名，适配器按 resolution 拼接 sd2_manxue_720p/1080p/2k/4k。'
      ),
      (
        'sd2_manxue_fast',
        'sd2_manxue Fast',
        'sd2_manxue_fast',
        'globalaiopc_sd2_manxue',
        '/v1/sd2_manxue/videos',
        '["video.text_to_video","video.image_to_video","video.first_last_frame_to_video","video.reference_image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"lastFrame":true,"referenceImages":true,"referenceVideo":false,"referenceAudio":true,"audio":true,"asyncPolling":true,"modelFamily":"sd2_manxue","membershipPriorityEligible":true}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"首帧图","type":"file","required":false},"lastFrame":{"label":"尾帧图","type":"file","required":false},"referenceImages":{"label":"参考图","type":"file[]","required":false,"maximum":9},"referenceAudio":{"label":"参考音频","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"ratio","required":false,"options":["21:9","16:9","4:3","1:1","3:4","9:16"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720p","1080p"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"integer","providerKey":"duration","required":false,"minimum":4,"maximum":15}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":5}'::jsonb,
        '{"unit":"video","baseCredits":120,"durationMultipliers":{"4":0.9,"5":1,"10":1.8,"15":2.6},"resolutionMultipliers":{"720p":1,"1080p":1.35}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":9,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsReferenceImages":true,"supportsReferenceAudio":true,"minDurationSec":4,"maxDurationSec":15,"supportedRatios":["21:9","16:9","4:3","1:1","3:4","9:16"],"supportedResolutions":["720p","1080p"],"allowedMimeTypes":["image/jpeg","image/png","image/webp","audio/mpeg","audio/wav"]}'::jsonb,
        '{"label":"sd2_manxue Fast","group":"GlobalAiOpc","recommended":true,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","modelKind":"video.reference","modelKindLabel":"参考生视频","supportedModes":["text_to_video","image_to_video","first_last_frame_to_video","reference_image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/sd2-manxue/sd2-manxue-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        31,
        'GlobalAiOpc sd2_manxue fast 系列。平台配置使用统一模型名，适配器按 resolution 拼接 sd2_manxue_fast_720p/1080p。'
      ),
      (
        'sd2_manxue_video',
        'sd2_manxue 视频参考',
        'sd2_manxue_video',
        'globalaiopc_sd2_manxue',
        '/v1/sd2_manxue/videos',
        '["video.text_to_video","video.image_to_video","video.first_last_frame_to_video","video.reference_image_to_video","video.video_to_video","video.image_video_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"lastFrame":true,"referenceImages":true,"referenceVideo":true,"referenceAudio":true,"audio":true,"asyncPolling":true,"modelFamily":"sd2_manxue","membershipPriorityEligible":true}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"首帧图","type":"file","required":false},"lastFrame":{"label":"尾帧图","type":"file","required":false},"referenceImages":{"label":"参考图","type":"file[]","required":false,"maximum":9},"sourceVideo":{"label":"参考视频","type":"file","required":false},"referenceAudio":{"label":"参考音频","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"ratio","required":false,"options":["21:9","16:9","4:3","1:1","3:4","9:16"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720p","1080p","2k","4k"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"integer","providerKey":"duration","required":false,"minimum":4,"maximum":15}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":5}'::jsonb,
        '{"unit":"video","baseCredits":180,"durationMultipliers":{"4":0.9,"5":1,"10":1.8,"15":2.6},"resolutionMultipliers":{"720p":1,"1080p":1.35,"2k":1.8,"4k":2.6}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":9,"maxReferenceVideos":3,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsReferenceImages":true,"supportsSourceVideo":true,"supportsReferenceAudio":true,"minDurationSec":4,"maxDurationSec":15,"supportedRatios":["21:9","16:9","4:3","1:1","3:4","9:16"],"supportedResolutions":["720p","1080p","2k","4k"],"allowedMimeTypes":["image/jpeg","image/png","image/webp","video/mp4","audio/mpeg","audio/wav"]}'::jsonb,
        '{"label":"sd2_manxue 视频参考","group":"GlobalAiOpc","recommended":true,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","modelKind":"video.reference","modelKindLabel":"参考生视频","supportedModes":["text_to_video","image_to_video","first_last_frame_to_video","reference_image_to_video","video_to_video","image_video_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/sd2-manxue/sd2-manxue-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        32,
        'GlobalAiOpc sd2_manxue video 系列。平台配置使用统一模型名，适配器按 resolution 拼接 sd2_manxue_video_720p/1080p/2k/4k。'
      ),
      (
        'sd2_manxue_video_fast',
        'sd2_manxue 视频参考 Fast',
        'sd2_manxue_video_fast',
        'globalaiopc_sd2_manxue',
        '/v1/sd2_manxue/videos',
        '["video.text_to_video","video.image_to_video","video.first_last_frame_to_video","video.reference_image_to_video","video.video_to_video","video.image_video_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"lastFrame":true,"referenceImages":true,"referenceVideo":true,"referenceAudio":true,"audio":true,"asyncPolling":true,"modelFamily":"sd2_manxue","membershipPriorityEligible":true}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"首帧图","type":"file","required":false},"lastFrame":{"label":"尾帧图","type":"file","required":false},"referenceImages":{"label":"参考图","type":"file[]","required":false,"maximum":9},"sourceVideo":{"label":"参考视频","type":"file","required":false},"referenceAudio":{"label":"参考音频","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"ratio","required":false,"options":["21:9","16:9","4:3","1:1","3:4","9:16"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720p","1080p"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"integer","providerKey":"duration","required":false,"minimum":4,"maximum":15}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":5}'::jsonb,
        '{"unit":"video","baseCredits":140,"durationMultipliers":{"4":0.9,"5":1,"10":1.8,"15":2.6},"resolutionMultipliers":{"720p":1,"1080p":1.35}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":9,"maxReferenceVideos":3,"supportsFirstFrame":true,"supportsLastFrame":true,"supportsReferenceImages":true,"supportsSourceVideo":true,"supportsReferenceAudio":true,"minDurationSec":4,"maxDurationSec":15,"supportedRatios":["21:9","16:9","4:3","1:1","3:4","9:16"],"supportedResolutions":["720p","1080p"],"allowedMimeTypes":["image/jpeg","image/png","image/webp","video/mp4","audio/mpeg","audio/wav"]}'::jsonb,
        '{"label":"sd2_manxue 视频参考 Fast","group":"GlobalAiOpc","recommended":true,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","modelKind":"video.reference","modelKindLabel":"参考生视频","supportedModes":["text_to_video","image_to_video","first_last_frame_to_video","reference_image_to_video","video_to_video","image_video_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/sd2-manxue/sd2-manxue-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        33,
        'GlobalAiOpc sd2_manxue video fast 系列。平台配置使用统一模型名，适配器按 resolution 拼接 sd2_manxue_video_fast_720p/1080p。'
      ),
      (
        'openAiSora2Plus',
        'Sora 2 Plus',
        'openAiSora2Plus',
        'globalaiopc_sora',
        '/v1/sora/videos',
        '["video.text_to_video","video.image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"sora"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"参考图","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"aspect_ratio","required":false,"options":["16:9","9:16"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"enum","providerKey":"seconds","required":false,"options":[4,8,12]},"size":{"label":"视频尺寸","type":"enum","required":false,"options":["1280x720","720x1280"]}}'::jsonb,
        '{"aspectRatio":"16:9","durationSec":8}'::jsonb,
        '{"unit":"video","baseCredits":220,"durationMultipliers":{"4":0.8,"8":1,"12":1.4}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":1,"supportsFirstFrame":true,"minDurationSec":4,"maxDurationSec":12,"supportedDurations":[4,8,12],"supportedRatios":["16:9","9:16"],"supportedSizes":["1280x720","720x1280"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Sora 2 Plus","group":"GlobalAiOpc Sora","recommended":true,"visible":true,"pipeline":"video","videoCategory":"first_frame","videoCategoryLabel":"首帧视频","supportedModes":["text_to_video","image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/sora/sora-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        34,
        'GlobalAiOpc Sora 2 Plus，支持 4/8/12 秒与最多 1 张参考图。'
      ),
      (
        'openAiSora2Pro',
        'Sora 2 Pro',
        'openAiSora2Pro',
        'globalaiopc_sora',
        '/v1/sora/videos',
        '["video.text_to_video","video.image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"sora"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"参考图","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"aspect_ratio","required":false,"options":["16:9","9:16"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"enum","providerKey":"seconds","required":false,"options":[4,8,12]},"size":{"label":"视频尺寸","type":"enum","required":false,"options":["1280x720","720x1280"]}}'::jsonb,
        '{"aspectRatio":"16:9","durationSec":8}'::jsonb,
        '{"unit":"video","baseCredits":260,"durationMultipliers":{"4":0.8,"8":1,"12":1.4}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":1,"supportsFirstFrame":true,"minDurationSec":4,"maxDurationSec":12,"supportedDurations":[4,8,12],"supportedRatios":["16:9","9:16"],"supportedSizes":["1280x720","720x1280"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Sora 2 Pro","group":"GlobalAiOpc Sora","recommended":false,"visible":true,"pipeline":"video","videoCategory":"first_frame","videoCategoryLabel":"首帧视频","supportedModes":["text_to_video","image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/sora/sora-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        35,
        'GlobalAiOpc Sora 2 Pro，支持 4/8/12 秒与最多 1 张参考图。'
      ),
      (
        'grok_video3',
        'Grok Video 3',
        'grok_video3',
        'globalaiopc_grok',
        '/v1/grok/videos',
        '["video.text_to_video","video.image_to_video","video.reference_image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"grok"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"referenceImages":{"label":"参考图","type":"file[]","required":false,"maximum":7},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"aspect_ratio","required":false,"options":["16:9","9:16","1:1","3:2","2:3"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["480p","720p"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"integer","providerKey":"duration","required":false,"minimum":6,"maximum":30}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":10}'::jsonb,
        '{"unit":"video","baseCredits":180,"durationMultipliers":{"6":0.8,"10":1,"12":1.2,"16":1.6,"20":2,"30":3},"resolutionMultipliers":{"480p":0.8,"720p":1}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":7,"supportsFirstFrame":true,"supportsReferenceImages":true,"minDurationSec":6,"maxDurationSec":30,"supportedRatios":["16:9","9:16","1:1","3:2","2:3"],"supportedResolutions":["480p","720p"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Grok Video 3","group":"GlobalAiOpc Grok","recommended":true,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","supportedModes":["text_to_video","image_to_video","reference_image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/grok/grok-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        36,
        'GlobalAiOpc Grok Video 3，支持文生视频和图生视频。'
      ),
      (
        'grok_video3_pro',
        'Grok Video 3 Pro',
        'grok_video3_pro',
        'globalaiopc_grok',
        '/v1/grok/videos',
        '["video.text_to_video","video.image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"grok"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"参考图","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"aspect_ratio","required":false,"options":["16:9"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720p"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"enum","providerKey":"duration","required":false,"options":[10]}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":10}'::jsonb,
        '{"unit":"video","baseCredits":220}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":1,"supportsFirstFrame":true,"minDurationSec":10,"maxDurationSec":10,"supportedDurations":[10],"supportedRatios":["16:9"],"supportedResolutions":["720p"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Grok Video 3 Pro","group":"GlobalAiOpc Grok","recommended":false,"visible":true,"pipeline":"video","videoCategory":"first_frame","videoCategoryLabel":"首帧视频","supportedModes":["text_to_video","image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/grok/grok-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        37,
        'GlobalAiOpc Grok Video 3 Pro，固定 10 秒。'
      ),
      (
        'grok_video3_max',
        'Grok Video 3 Max',
        'grok_video3_max',
        'globalaiopc_grok',
        '/v1/grok/videos',
        '["video.text_to_video","video.image_to_video","video.reference_image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"grok"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"referenceImages":{"label":"参考图","type":"file[]","required":false,"maximum":5},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"aspect_ratio","required":false,"options":["16:9","9:16","1:1"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["480p","720p"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"enum","providerKey":"duration","required":false,"options":[6,10,12,16,20,30]}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":10}'::jsonb,
        '{"unit":"video","baseCredits":260,"durationMultipliers":{"6":0.8,"10":1,"12":1.2,"16":1.6,"20":2,"30":3},"resolutionMultipliers":{"480p":0.8,"720p":1}}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":5,"supportsFirstFrame":true,"supportsReferenceImages":true,"supportedDurations":[6,10,12,16,20,30],"supportedRatios":["16:9","9:16","1:1"],"supportedResolutions":["480p","720p"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Grok Video 3 Max","group":"GlobalAiOpc Grok","recommended":false,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","supportedModes":["text_to_video","image_to_video","reference_image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/grok/grok-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        38,
        'GlobalAiOpc Grok Video 3 Max，支持 6/10/12/16/20/30 秒。'
      ),
      (
        'grok_video1.5_pro',
        'Grok Video 1.5 Pro',
        'grok_video1.5_pro',
        'globalaiopc_grok',
        '/v1/grok/videos',
        '["video.text_to_video","video.image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"grok"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"firstFrame":{"label":"参考图","type":"file","required":false},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"aspect_ratio","required":false,"options":["16:9"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720p"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"enum","providerKey":"duration","required":false,"options":[10]}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":10}'::jsonb,
        '{"unit":"video","baseCredits":220}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":1,"supportsFirstFrame":true,"minDurationSec":10,"maxDurationSec":10,"supportedDurations":[10],"supportedRatios":["16:9"],"supportedResolutions":["720p"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Grok Video 1.5 Pro","group":"GlobalAiOpc Grok","recommended":false,"visible":true,"pipeline":"video","videoCategory":"first_frame","videoCategoryLabel":"首帧视频","supportedModes":["text_to_video","image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/grok/grok-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        39,
        'GlobalAiOpc Grok Video 1.5 Pro，固定 10 秒。'
      ),
      (
        'grok_video3_stable',
        'Grok Video 3 Stable',
        'grok_video3_stable',
        'globalaiopc_grok',
        '/v1/grok/videos',
        '["video.text_to_video","video.image_to_video","video.reference_image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"grok"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2000},"referenceImages":{"label":"参考图","type":"file[]","required":false,"maximum":7},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"aspect_ratio","required":false,"options":["16:9","9:16","3:2","2:3","1:1"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720p"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"enum","providerKey":"duration","required":false,"options":[10]}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720p","durationSec":10}'::jsonb,
        '{"unit":"video","baseCredits":180}'::jsonb,
        '{"maxPromptLength":2000,"maxReferences":7,"supportsFirstFrame":true,"supportsReferenceImages":true,"minDurationSec":10,"maxDurationSec":10,"supportedDurations":[10],"supportedRatios":["16:9","9:16","3:2","2:3","1:1"],"supportedResolutions":["720p"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Grok Video 3 Stable","group":"GlobalAiOpc Grok","recommended":false,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","supportedModes":["text_to_video","image_to_video","reference_image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/grok/grok-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        40,
        'GlobalAiOpc Grok Video 3 Stable，固定 10 秒，仅 720p。'
      ),
      (
        'globalaiopc-happyhorse-r2v',
        'Happy Horse 参考生视频',
        'happyhorse-1.0-r2v',
        'globalaiopc_happyhorse_r2v',
        '/v1/happyhorse-r2v/videos',
        '["video.image_to_video","video.reference_image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"happyhorse"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2500},"referenceImages":{"label":"参考图","type":"file[]","required":true,"minimum":1,"maximum":9},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"ratio","required":false,"options":["16:9","9:16","1:1","4:3","3:4","4:5","5:4","9:21","21:9"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720P","1080P"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"integer","providerKey":"duration","required":false,"minimum":3,"maximum":15},"seed":{"label":"随机种子","type":"integer","required":false,"minimum":0,"maximum":2147483647}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720P","durationSec":5,"seed":0}'::jsonb,
        '{"unit":"video","baseCredits":140,"durationMultipliers":{"3":0.8,"5":1,"10":1.8,"15":2.6},"resolutionMultipliers":{"720P":1,"1080P":1.35}}'::jsonb,
        '{"maxPromptLength":2500,"maxReferences":9,"requiresReferenceImages":true,"supportsReferenceImages":true,"minDurationSec":3,"maxDurationSec":15,"supportedRatios":["16:9","9:16","1:1","4:3","3:4","4:5","5:4","9:21","21:9"],"supportedResolutions":["720P","1080P"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Happy Horse 参考生视频","group":"GlobalAiOpc Happy Horse","recommended":false,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","modelKind":"video.reference","modelKindLabel":"参考生视频","supportedModes":["image_to_video","reference_image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/happyhorse/happyhorse-r2v-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        41,
        'GlobalAiOpc Happy Horse 参考生视频标准版。为避免覆盖阿里百炼同名模型，平台模型编码使用 globalaiopc-happyhorse-r2v。'
      ),
      (
        'globalaiopc-happyhorse-r2v-economy',
        'Happy Horse 参考生视频 Economy',
        'happyhorse-1.0-r2v-economy',
        'globalaiopc_happyhorse_r2v',
        '/v1/happyhorse-r2v/videos',
        '["video.image_to_video","video.reference_image_to_video"]'::jsonb,
        '{"prompt":true,"firstFrame":true,"referenceImages":true,"audio":false,"asyncPolling":true,"modelFamily":"happyhorse"}'::jsonb,
        '{"prompt":{"label":"提示词","type":"string","required":true,"maxLength":2500},"referenceImages":{"label":"参考图","type":"file[]","required":true,"minimum":1,"maximum":9},"aspectRatio":{"label":"视频比例","type":"enum","providerKey":"ratio","required":false,"options":["16:9","9:16","1:1","4:3","3:4","4:5","5:4","9:21","21:9"],"adminEditableOptions":true},"resolution":{"label":"分辨率","type":"enum","required":false,"options":["720P","1080P"],"adminEditableOptions":true},"durationSec":{"label":"视频时长","type":"integer","providerKey":"duration","required":false,"minimum":3,"maximum":15},"seed":{"label":"随机种子","type":"integer","required":false,"minimum":0,"maximum":2147483647}}'::jsonb,
        '{"aspectRatio":"16:9","resolution":"720P","durationSec":5,"seed":0}'::jsonb,
        '{"unit":"video","baseCredits":110,"durationMultipliers":{"3":0.8,"5":1,"10":1.8,"15":2.6},"resolutionMultipliers":{"720P":1,"1080P":1.35}}'::jsonb,
        '{"maxPromptLength":2500,"maxReferences":9,"requiresReferenceImages":true,"supportsReferenceImages":true,"minDurationSec":3,"maxDurationSec":15,"supportedRatios":["16:9","9:16","1:1","4:3","3:4","4:5","5:4","9:21","21:9"],"supportedResolutions":["720P","1080P"],"allowedMimeTypes":["image/jpeg","image/png","image/webp"]}'::jsonb,
        '{"label":"Happy Horse 参考生视频 Economy","group":"GlobalAiOpc Happy Horse","recommended":false,"visible":true,"pipeline":"video","videoCategory":"reference","videoCategoryLabel":"参考生视频","modelKind":"video.reference","modelKindLabel":"参考生视频","supportedModes":["image_to_video","reference_image_to_video"],"providerDocUrl":"https://docs.globalaiopc.com/api-reference/video/happyhorse/happyhorse-r2v-create","parameterDisplayLanguage":"zh-CN"}'::jsonb,
        42,
        'GlobalAiOpc Happy Horse 参考生视频实惠版。'
      )
  ) AS v(model_code, display_name, provider_model, request_format, create_task_endpoint, task_modes_json, capabilities_json, parameter_schema_json, default_params_json, pricing_json, limits_json, ui_config_json, sort_order, remark)
)
INSERT INTO ai_model_configs (
  id,
  model_code,
  display_name,
  provider_name,
  provider_model,
  provider_protocol,
  invocation_mode,
  media_type,
  task_modes_json,
  capabilities_json,
  parameter_schema_json,
  default_params_json,
  provider_config_json,
  pricing_json,
  limits_json,
  ui_config_json,
  status,
  sort_order,
  remark
)
SELECT
  gen_random_uuid(),
  globalaiopc_configs.model_code,
  globalaiopc_configs.display_name,
  'GlobalAiOpc',
  globalaiopc_configs.provider_model,
  'globalaiopc_video',
  'async_polling',
  'video',
  globalaiopc_configs.task_modes_json,
  globalaiopc_configs.capabilities_json,
  globalaiopc_configs.parameter_schema_json,
  globalaiopc_configs.default_params_json,
  jsonb_build_object(
    'baseURL', 'https://zcbservice.aizfw.cn/kyyReactApiServer',
    'createTaskEndpoint', globalaiopc_configs.create_task_endpoint,
    'queryTaskEndpoint', '/v1/result/{taskId}',
    'apiKeyEnv', COALESCE(NULLIF(existing.provider_config_json->>'apiKeyEnv', ''), 'GLOBAL_AI_OPC_API_KEY'),
    'requestFormat', globalaiopc_configs.request_format,
    'timeoutMs', 120000
  ),
  globalaiopc_configs.pricing_json,
  globalaiopc_configs.limits_json,
  globalaiopc_configs.ui_config_json,
  'active',
  globalaiopc_configs.sort_order,
  globalaiopc_configs.remark
FROM globalaiopc_configs
LEFT JOIN ai_model_configs AS existing
  ON existing.model_code = globalaiopc_configs.model_code
ON CONFLICT (model_code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  provider_name = EXCLUDED.provider_name,
  provider_model = EXCLUDED.provider_model,
  provider_protocol = EXCLUDED.provider_protocol,
  invocation_mode = EXCLUDED.invocation_mode,
  media_type = EXCLUDED.media_type,
  task_modes_json = EXCLUDED.task_modes_json,
  capabilities_json = EXCLUDED.capabilities_json,
  parameter_schema_json = EXCLUDED.parameter_schema_json,
  default_params_json = EXCLUDED.default_params_json,
  provider_config_json = EXCLUDED.provider_config_json,
  pricing_json = EXCLUDED.pricing_json,
  limits_json = EXCLUDED.limits_json,
  ui_config_json = EXCLUDED.ui_config_json,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  remark = EXCLUDED.remark,
  updated_at = now();

INSERT INTO ai_model_dispatch_policies (
  id,
  model_config_id,
  queue_backend,
  submit_queue_name,
  poll_queue_name,
  finalize_queue_name,
  dead_letter_queue_name,
  job_id_template,
  bullmq_job_options_json,
  submit_concurrency_limit,
  provider_rpm_limit,
  provider_concurrent_limit,
  polling_interval_ms,
  polling_concurrency_limit,
  polling_backoff_json,
  retry_policy_json,
  circuit_breaker_json,
  status
)
SELECT
  gen_random_uuid(),
  model.id,
  'bullmq',
  'generation-submit-video',
  'generation-poll-video',
  'generation-finalize-artifact',
  'generation-dead-letter',
  'generation:video:{stage}:{taskId}',
  '{"attempts":3,"backoff":{"type":"exponential","delay":3000},"removeOnComplete":{"age":86400,"count":10000},"removeOnFail":{"age":604800,"count":50000}}'::jsonb,
  5,
  60,
  5,
  15000,
  20,
  '{"strategy":"fixed","intervalMs":15000,"maxAttempts":240}'::jsonb,
  '{"submitAttempts":3,"pollAttempts":240,"finalizeAttempts":3}'::jsonb,
  '{"failureThreshold":5,"windowMs":60000,"cooldownMs":120000}'::jsonb,
  'active'
FROM ai_model_configs AS model
WHERE model.model_code IN (
  'sd2_manxue',
  'sd2_manxue_fast',
  'sd2_manxue_video',
  'sd2_manxue_video_fast',
  'openAiSora2Plus',
  'openAiSora2Pro',
  'grok_video3',
  'grok_video3_pro',
  'grok_video3_max',
  'grok_video1.5_pro',
  'grok_video3_stable',
  'globalaiopc-happyhorse-r2v',
  'globalaiopc-happyhorse-r2v-economy'
)
ON CONFLICT (model_config_id) DO UPDATE SET
  submit_queue_name = EXCLUDED.submit_queue_name,
  poll_queue_name = EXCLUDED.poll_queue_name,
  finalize_queue_name = EXCLUDED.finalize_queue_name,
  dead_letter_queue_name = EXCLUDED.dead_letter_queue_name,
  job_id_template = EXCLUDED.job_id_template,
  bullmq_job_options_json = EXCLUDED.bullmq_job_options_json,
  submit_concurrency_limit = EXCLUDED.submit_concurrency_limit,
  provider_rpm_limit = EXCLUDED.provider_rpm_limit,
  provider_concurrent_limit = EXCLUDED.provider_concurrent_limit,
  polling_interval_ms = EXCLUDED.polling_interval_ms,
  polling_concurrency_limit = EXCLUDED.polling_concurrency_limit,
  polling_backoff_json = EXCLUDED.polling_backoff_json,
  retry_policy_json = EXCLUDED.retry_policy_json,
  circuit_breaker_json = EXCLUDED.circuit_breaker_json,
  status = EXCLUDED.status,
  updated_at = now();
