-- Retire the marketing console and its dedicated data model.
-- Keep shared model-gateway audit columns introduced by the historical
-- marketing migration; they are used by non-marketing administrator flows.
DROP TABLE IF EXISTS
  marketing_competitor_collection_runs,
  marketing_competitor_collection_jobs,
  marketing_generation_skills,
  marketing_execution_owner_bindings,
  marketing_knowledge_lineage,
  marketing_generation_runs,
  marketing_component_admissions,
  marketing_agent_provider_approvals,
  marketing_agent_usage_records,
  marketing_research_request_log,
  marketing_executor_alerts,
  marketing_brand_profiles,
  marketing_agent_steps,
  marketing_agent_runs,
  marketing_research_source_policies,
  marketing_research_briefs,
  marketing_metric_observations,
  marketing_trend_patterns,
  marketing_attention_cases,
  marketing_content_manual_reviews,
  marketing_compliance_checks,
  marketing_platform_capability_profiles,
  marketing_knowledge_segments,
  marketing_knowledge_documents,
  marketing_audit_events,
  marketing_publish_events,
  marketing_request_nonces,
  marketing_executor_keys,
  marketing_executors,
  marketing_delivery_assets,
  marketing_publish_deliveries,
  marketing_publish_jobs,
  marketing_content_variants,
  marketing_campaigns,
  marketing_sources,
  marketing_projects
CASCADE;
